# syntax=docker/dockerfile:1
# Build Next.js frontend

FROM node:20-alpine AS base
RUN corepack enable && corepack prepare pnpm@9.15.0 --activate
WORKDIR /app

FROM base AS deps
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/web/package.json apps/web/
COPY apps/admin/package.json apps/admin/
COPY packages/config/package.json packages/config/
COPY packages/sdk/package.json packages/sdk/
COPY packages/ui/package.json packages/ui/
COPY services/allocator/package.json services/allocator/
COPY services/quote/package.json services/quote/
COPY services/indexer/package.json services/indexer/
RUN pnpm install --frozen-lockfile --ignore-scripts \
  --filter "@novex/web..."

FROM deps AS build
ARG NEXT_PUBLIC_USE_TESTNET=true
ARG NEXT_PUBLIC_PRIVY_APP_ID
ARG NEXT_PUBLIC_VAULT_ADDRESS
ARG NEXT_PUBLIC_RECEIPT_TOKEN_ADDRESS
ARG NEXT_PUBLIC_FACTORY_ADDRESS
ARG NEXT_PUBLIC_PAIR_FACTORY_ADDRESS
ARG NEXT_PUBLIC_EXPLORER_URL
ARG NEXT_PUBLIC_ALLOCATOR_URL=http://localhost:3001
ARG NEXT_PUBLIC_QUOTE_URL=http://localhost:3002
ARG NEXT_PUBLIC_INDEXER_URL=http://localhost:3003
ARG NEXT_PUBLIC_ROBINHOOD_TESTNET_RPC_URL
ARG NEXT_PUBLIC_ROBINHOOD_RPC_URL
ARG ROBINHOOD_TESTNET_RPC_URL
ARG ROBINHOOD_RPC_URL

ENV NEXT_PUBLIC_USE_TESTNET=${NEXT_PUBLIC_USE_TESTNET}
ENV ROBINHOOD_TESTNET_RPC_URL=${ROBINHOOD_TESTNET_RPC_URL}
ENV ROBINHOOD_RPC_URL=${ROBINHOOD_RPC_URL}
ENV NEXT_PUBLIC_PRIVY_APP_ID=${NEXT_PUBLIC_PRIVY_APP_ID}
ENV NEXT_PUBLIC_VAULT_ADDRESS=${NEXT_PUBLIC_VAULT_ADDRESS}
ENV NEXT_PUBLIC_RECEIPT_TOKEN_ADDRESS=${NEXT_PUBLIC_RECEIPT_TOKEN_ADDRESS}
ENV NEXT_PUBLIC_FACTORY_ADDRESS=${NEXT_PUBLIC_FACTORY_ADDRESS}
ENV NEXT_PUBLIC_PAIR_FACTORY_ADDRESS=${NEXT_PUBLIC_PAIR_FACTORY_ADDRESS}
ENV NEXT_PUBLIC_EXPLORER_URL=${NEXT_PUBLIC_EXPLORER_URL}
ENV NEXT_PUBLIC_ALLOCATOR_URL=${NEXT_PUBLIC_ALLOCATOR_URL}
ENV NEXT_PUBLIC_QUOTE_URL=${NEXT_PUBLIC_QUOTE_URL}
ENV NEXT_PUBLIC_INDEXER_URL=${NEXT_PUBLIC_INDEXER_URL}
ENV NEXT_PUBLIC_ROBINHOOD_TESTNET_RPC_URL=${NEXT_PUBLIC_ROBINHOOD_TESTNET_RPC_URL}
ENV NEXT_PUBLIC_ROBINHOOD_RPC_URL=${NEXT_PUBLIC_ROBINHOOD_RPC_URL}

COPY tsconfig.base.json ./
COPY packages/config packages/config
COPY packages/sdk packages/sdk
COPY packages/ui packages/ui
COPY apps/web apps/web

RUN pnpm --filter @novex/config build \
 && pnpm --filter @novex/sdk build \
 && pnpm --filter @novex/ui build \
 && pnpm --filter @novex/web build

FROM base AS runner
ENV NODE_ENV=production
WORKDIR /app

COPY --from=build /app/apps/web/.next/standalone ./
COPY --from=build /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=build /app/apps/web/public ./apps/web/public

USER node
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "apps/web/server.js"]
